Refactor snap to work with core18. (#73)
Refactor snap to work with core18.

Giving the snapcraft.yaml a base property helps tremendously with the
efficiency of the build process, and I believe that it puts us in a
better position to reliably support non Ubuntu distros going forward.

This also bases us on long supported bionic libraries, and gives us a
nice place to work from as we add Python 3 and Stein support, as well
as general polish and fixes.

diff --git a/snapcraft.yaml b/snapcraft.yaml
--- a/snapcraft.yaml
+++ b/snapcraft.yaml
@@ -1,5 +1,6 @@
 name: microstack
 version: rocky
+base: core18
 summary: OpenStack on your laptop.
 description: |
   Microstack gives you an easy way to develop and test OpenStack
@@ -229,6 +230,9 @@ apps:
     daemon: simple
     environment:
       LD_LIBRARY_PATH: $SNAP/lib:$SNAP/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/usr/lib:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio
+  virtlogd:
+    command: virtlogd
+    daemon: simple
   virsh:
     command: virsh
 
@@ -315,7 +319,8 @@ parts:
   openstack-projects:
     plugin: python
     python-version: python2
-    constraints: https://raw.githubusercontent.com/openstack/requirements/stable/rocky/upper-constraints.txt
+    constraints:
+      - https://raw.githubusercontent.com/openstack/requirements/stable/rocky/upper-constraints.txt
     source: http://tarballs.openstack.org/keystone/keystone-stable-rocky.tar.gz
     python-packages:
       - libvirt-python
@@ -333,6 +338,7 @@ parts:
       - python-swiftclient
     build-packages:
       - gcc
+      - git
       - libffi-dev
       - libssl-dev
       - libxml2-dev
@@ -342,19 +348,17 @@ parts:
       - conntrack
       - coreutils
       - haproxy
-    override-build: |
-      # Ensure libvirt is discovered from previous built part
-      export PKG_CONFIG_PATH=$SNAPCRAFT_STAGE/lib/pkgconfig
-      snapcraftctl build
+      - libpython2.7
     override-prime: |
       snapcraftctl prime
+      # Uncomment the below line for better python-libvirt debugging output.
+      # patch --batch --forward --strip 1 --input ../project/patches/nova/nova_log_error.patch
       # Now that everything is built, let's disable user site-packages
       # as stated in PEP-0370
       sed -i usr/lib/python2.7/site.py -e 's/^ENABLE_USER_SITE = None$/ENABLE_USER_SITE = False/'
       # This is the last step, let's now compile all our pyc files.
       # Ignore errors due to syntax issues in foobar python 2.
       ./usr/bin/python2.7 -m compileall . || true
-
   keystone-config:
     after: [openstack-projects]
     plugin: dump
@@ -448,7 +452,7 @@ parts:
 
   openvswitch:
     # TODO: figure out a better way to fetch the version
-    source: http://openvswitch.org/releases/openvswitch-2.10.1.tar.gz
+    source: http://openvswitch.org/releases/openvswitch-2.10.2.tar.gz
     plugin: autotools
     build-packages:
       - libssl-dev
@@ -522,15 +526,13 @@ parts:
       done
       snapcraftctl build
 
-  libxml2:
-    source: http://xmlsoft.org/sources/libxml2-2.9.4.tar.gz
-    plugin: autotools
-
   # libvirt/qemu
   qemu:
     source: .
-    source-subdir: qemu-2.5+dfsg
+    source-subdir: qemu-2.11+dfsg
     plugin: autotools
+    after:
+      - openstack-projects
     stage-packages:
       - seabios
       - ipxe-qemu
@@ -540,14 +542,14 @@ parts:
       - libasound2
       - libasyncns0
       - libbluetooth3
-      - libboost-iostreams1.58.0
-      - libboost-random1.58.0
-      - libboost-system1.58.0
-      - libboost-thread1.58.0
+      - libboost-iostreams1.62.0
+      - libboost-random1.62.0
+      - libboost-system1.62.0
+      - libboost-thread1.62.0
       - libcaca0
       - libfdt1
       - libflac8
-      - libiscsi2
+      - libiscsi7
       - libjpeg-turbo8
       - libnspr4
       - libnss3
@@ -567,6 +569,7 @@ parts:
       - libxau6
       - libxcb1
       - libxdmcp6
+      - libxen-dev
       - libxext6
     build-packages:
       - acpica-tools
@@ -611,9 +614,12 @@ parts:
       - --enable-system
       - --target-list=x86_64-softmmu
     override-build: |
-      wget http://archive.ubuntu.com/ubuntu/pool/main/q/qemu/qemu_2.5+dfsg.orig.tar.xz
-      wget http://archive.ubuntu.com/ubuntu/pool/main/q/qemu/qemu_2.5+dfsg-5ubuntu10.38.debian.tar.xz
-      wget http://archive.ubuntu.com/ubuntu/pool/main/q/qemu/qemu_2.5+dfsg-5ubuntu10.38.dsc
+      # Clean up old install
+      rm -R qemu-2.* || true
+      # Download sources and patch
+      wget http://archive.ubuntu.com/ubuntu/pool/main/q/qemu/qemu_2.11+dfsg.orig.tar.xz
+      wget http://archive.ubuntu.com/ubuntu/pool/main/q/qemu/qemu_2.11+dfsg-1ubuntu7.14.debian.tar.xz
+      wget http://archive.ubuntu.com/ubuntu/pool/main/q/qemu/qemu_2.11+dfsg-1ubuntu7.14.dsc
       dpkg-source -x qemu_*.dsc
       snapcraftctl build
     organize:
@@ -630,7 +636,8 @@ parts:
 
   libvirt:
     source: .
-    source-subdir: libvirt-1.3.1
+    source-subdir: libvirt-4.0.0
+    after: [openstack-projects, qemu]
     plugin: autotools
     build-packages:
     - libxml2-dev
@@ -648,19 +655,22 @@ parts:
     - libpciaccess-dev
     - libnl-3-dev
     - libnl-route-3-dev
+    - libxml2-utils
     - uuid-dev
     - try: [libnuma-dev]
+    - python-all
+    - python-six
     - wget
     - dpkg-dev
+    - xsltproc
     stage-packages:
-    - try: [dmidecode]
+    - dmidecode
     - dnsmasq
-    - dnsmasq-utils
-    - ebtables
     - libxml2
     - libyajl2
     - try: [libnuma1]
     - libcurl3-gnutls
+    - libpcap0.8
     - libpciaccess0
     configflags:
     - --with-qemu
@@ -687,12 +697,15 @@ parts:
     - DNSMASQ=/snap/$SNAPCRAFT_PROJECT_NAME/current/usr/sbin/dnsmasq
     - DMIDECODE=/snap/$SNAPCRAFT_PROJECT_NAME/current/usr/sbin/dmidecode
     - OVSVSCTL=/snap/$SNAPCRAFT_PROJECT_NAME/current/bin/ovs-vsctl
-    - EBTABLES_PATH=/snap/$SNAPCRAFT_PROJECT_NAME/current/sbin/ebtables
     - IPTABLES_PATH=/snap/$SNAPCRAFT_PROJECT_NAME/current/sbin/iptables
+    - IP6TABLES_PATH=/snap/$SNAPCRAFT_PROJECT_NAME/current/sbin/ip6tables
     override-build: |
-      wget http://archive.ubuntu.com/ubuntu/pool/main/libv/libvirt/libvirt_1.3.1.orig.tar.gz
-      wget http://archive.ubuntu.com/ubuntu/pool/main/libv/libvirt/libvirt_1.3.1-1ubuntu10.25.debian.tar.xz
-      wget http://archive.ubuntu.com/ubuntu/pool/main/libv/libvirt/libvirt_1.3.1-1ubuntu10.25.dsc
+      # Clean up old install
+      rm -R libvirt-4.0.* || true
+      # Download sources and patch
+      wget http://archive.ubuntu.com/ubuntu/pool/main/libv/libvirt/libvirt_4.0.0.orig.tar.xz
+      wget http://archive.ubuntu.com/ubuntu/pool/main/libv/libvirt/libvirt_4.0.0-1ubuntu8.10.debian.tar.xz
+      wget http://archive.ubuntu.com/ubuntu/pool/main/libv/libvirt/libvirt_4.0.0-1ubuntu8.10.dsc
       dpkg-source -x libvirt*.dsc
       snapcraftctl build
     organize:
@@ -733,13 +746,13 @@ parts:
   # Memcached Token Caching
   memcached:
     plugin: autotools
-    source: https://memcached.org/files/memcached-1.5.10.tar.gz
+    source: https://memcached.org/files/memcached-1.5.14.tar.gz
     build-packages:
       - libevent-dev
       - gcc
       - make
     stage-packages:
-      - libevent-2.0-5
+      - libevent-2.1-6
     override-build: |
       ./configure --prefix=$SNAPCRAFT_PART_INSTALL
       make
@@ -759,7 +772,7 @@ parts:
     source: https://www.kernel.org/pub/linux/utils/net/bridge-utils/bridge-utils-1.6.tar.gz
     plugin: autotools
   iproute2:
-    source: https://www.kernel.org/pub/linux/utils/net/iproute2/iproute2-4.9.0.tar.gz
+    source: https://www.kernel.org/pub/linux/utils/net/iproute2/iproute2-4.20.0.tar.gz
     plugin: autotools
     build-packages:
       - bison
@@ -773,7 +786,8 @@ parts:
     configflags:
       - --disable-nftables
       - --prefix=/snap/$SNAPCRAFT_PROJECT_NAME/current
-    install: |
+    override-build: |
+      snapcraftctl build
       cp --remove-destination $SNAPCRAFT_PART_INSTALL/snap/$SNAPCRAFT_PROJECT_NAME/current/sbin/xtables-multi \
         $SNAPCRAFT_PART_INSTALL/snap/$SNAPCRAFT_PROJECT_NAME/current/bin/iptables-xml
     organize:
